### ISSUE TITLE
Character valued features lead to unknown reason error

### ISSUE THREAD

**Issue by soerenkuenzel** [soerenkuenzel/forestry#12]
`foretry` throws an "c++ exception (unknown reason)" error, when one of the features is character valued. 
Automatically cast characters to factors or throw a more meaningful error that tells users to cast characters to factors.

```
library(forestry)
test_idx <- sample(nrow(iris), 3)
x_train <- iris[, -1]
y_train <- iris[, 1]

x_train$charCol <- sample(c('a', 'b'), nrow(iris), TRUE)
rf <- forestry(x = x_train, y = y_train) 

x_train$charCol <- as.factor(x_train$charCol)
rf <- forestry(x = x_train, y = y_train)
```
<simpleError in rcpp_cppDataFrameInterface(processed_x, y, categoricalFeatureCols_cpp,     linFeats, nObservations, numColumns): c++ exception (unknown reason)>

**Comment by edwardwliu** [comment]
Resolved in commit ba80502f9df8acf45ac2691a4b5efb9f233fdc30.
