### ISSUE TITLE
When testing and training data don't have the same columns the error is confusing

### ISSUE THREAD

**Issue by soerenkuenzel** [soerenkuenzel/forestry#17]
When the testing and training data don't have the same columns the error suggests that there is something wrong with categorical variables. This is a confusing behavior. 
See the example below. We should throw an error here saying that the column names should match.
```
library(forestry)

rf <- forestry(x = iris[, -1], 
               y = iris[, 1])
predict(rf, iris[, -1])
# works well

predict(rf, iris)
# Error: "Categorical columns are different between testing and training data."
```

**Comment by edwardwliu** [comment]
Duplicate of issue #3.
